#!/bin/bash

host=localhost

# log file
log="connection_test.log"
if [ -f $log ];
then
    echo "Older file $log exists, removing and creating new..."
    rm -rf $log
    touch $log
else
    echo "Creating log file"
    touch $log
fi

# running expect script.
# arg 1 is user, arg 2 is pass, arg 3 is host


for line in $(cat list_accounts)
do

user=`echo $line | cut -d"," -f1`
password=`echo $line | cut -d"," -f2`
echo $user
echo $password
# running expect script.
# arg 1 is user, arg 2 is pass, arg 3 is host 
./sftp_expect $user $password $host  >> $log

# checking log for connections 
if grep --quiet logout $log; then
    echo "$user [OK] connection successful" >> $log
else
    echo "$user [FAILED] connection failed" >> $log
    exit 1
fi

done
